environment:
  ELECTRON_RUN_AS_NODE: 1
  VSCODE_BUILD_VERBOSE: true

install:
  - ps: Install-Product node 7.4.0 x64
  - npm install -g npm --silent
  - npm install -g gulp mocha --silent
  - npm install

test_script:
  - node --version
  - npm --version
  - npm test

build: off